title: SSpace Website
email: sspace.iist@gmail.com
description: >- 
  for sspace website
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll


theme: minima
plugins:
  - jekyll-feed
