title: SSpace Website
email: sspace.iist@gmail.com
description: >- 
  for sspace website
baseurl: ""
url: "http://abhishek-arch.local:8000"
twitter_username: jekyllrb
github_username:  jekyll


theme: minima
plugins:
  - jekyll-feed


collections:
  students:
    output: true